title: 30,000 Leagues, a new podcast from The Policy Lab
description: A new podcast from The Policy Lab.

repository: thepolicylab/30000-leagues.git
github.pages_hostname: https://thirtythousandleagues.com

markdown: kramdown
highlighter: rouge
redcarpet:
  extensions: ["no_intra_emphasis", "fenced_code_blocks", "autolink", "strikethrough", "superscript", "with_toc_data"]

baseurl: /
port: 4060
url: //thirtythousandleagues.com
twitter_handle: 30000leagues


# Define some defaults
defaults:
  -
    values:
      layout: "page"
      author: "The Policy Lab"


# Permalink Configuration
permalink: /blog/:year/:month/:title

# Post types
collections:
  team:
    output: true
    permalink: /team/:name
  events:
    output: false
    permalink: /events/:name

# Exclude from _site build
exclude: ['.git',
  '.gitignore',
  'Gemfile',
  'Gemfile.lock',
  'CNAME',
  'LICENSE',
  'feed.xml',
  'team/README.md'
  ]


# Setting relative permalink to false. See http://jekyllrb.com/docs/upgrading/.
relative_permalinks: false

sass:
  sass_dir: _sass


# Plugins and extras
plugins:
- jekyll-autoprefixer
- jekyll-github-metadata
